#!/bin/bash

cd $(dirname $0)

if [ ! -d "$1" ]; then
	echo "invalid problem: $1"
	exit 1
fi

cd $1
docker build -t $1 .
echo "build complete, running..."

input_file=${2:-input.txt}
echo "reading from $input_file"
cat $input_file | docker run -i --rm $1
